### ISSUE TITLE
Build per-package-target

### ISSUE THREAD

**Issue by pinkforest** [yaws-rs/yaws#16]
There is unstable feature:
https://doc.rust-lang.org/cargo/reference/unstable.html#per-package-target

```toml
cargo-features = ["per-package-target"]

[package]
forced-target = "wasm32-unknown-unknown"
# and/or:
default-target = "wasm32-unknown-unknown"
```

When this thing stabilises maybe build Lunatic more easily so people don't need `--target wasm32-wasi`
- https://github.com/rust-lang/cargo/pull/9406
